### ISSUE TITLE
Dude

### ISSUE THREAD

**Issue by NotCacha-arg** [MinusKube/Netherboard#12]
I have a problem, I put that when a staff is activated the staffmode some lines are added and that works well but when the staff is deactivated the staffmode the lines do not leave the staff has to restart has to leave and re-enter

**Comment by MinusKube** [comment]
Hi, did you make sure your code removes the line from the scoreboard using `BPlayerBoard#remove(Integer)` when you deactivate your staff?

**Comment by NotCacha-arg** [comment]
Do you mean erase the scoreboard or the line?

**Comment by MinusKube** [comment]
The lines

**Comment by NotCacha-arg** [comment]
if(arraylist.staffmode.contains(p.getName())) {
            board.set("§7§m--------------------", 15);
            board.set("test);
        }else {
            board.set("§7§m--------------------", 15);
        }

Example for code xd

**Comment by MinusKube** [comment]
When you call `set`, you add or replace the lines, but nothing gets removed, you need to call the `remove` method for this
