### ISSUE TITLE
help for api

### ISSUE THREAD

**Issue by NotCacha** [MinusKube/Netherboard#13]
How can I make repeated lines work example

    - "&7&m--------------------"
    - "&fRank&7:"
    - "&d%player_rank%"
    - ""
    - "&fPlayers&7:"
    - "&d%bungee_total%"
    - ""
    - "&7&m-------&7&m-------------"

because only one line counts that is blank and the other does not

**Comment by MinusKube** [comment]
Hi, you can put colors in the end of lines, so they will be different, but still visually the same, for example: `"&1"` and `"&2"`.

**Comment by NotCacha** [comment]
But there is no way to do it without it?

**Comment by MinusKube** [comment]
Nope, it's a planned feature, but currently, it's the only way.
