### ISSUE TITLE
Why can't you create repeated lines like Bukkit?

### ISSUE THREAD

**Issue by nahubar** [MinusKube/Netherboard#16]
I know that to create the method BPlayerBoard.set ("Text", score);
You used the ScoreboardScore class, I know because I have used ScoreboardScore and it has had the same result as using the API, besides that in the NMS class you can see when you call ScoreboardScore, what I don't understand is why can't repeat lines like bukkit? Could you explain to me what Bukkit does to "repeat lines" if you have any idea? Thanks in advance.

**Comment by MinusKube** [comment]
The lines can't be repeated on Bukkit's Scoreboard neither.

**Comment by nahubar** [comment]
LOL, I was wrong, it is not possible with the bukkit api, but there are plugins that can, such as Scoreboard-revision https://www.spigotmc.org/resources/scoreboard.14754/update?update=146127
Well, I am sorry I wasted my time, my memory has failed, although I may have done something wrong when I was testing the code.

**Comment by MinusKube** [comment]
Yeah, they just add a color at the end of the line to make it like they are two different lines, but visually the same. On the current version of Netherboard, you'll need to do it manually.

**Comment by toxamin** [comment]
that plugin uses teams.

**Comment by hswhsw610** [comment]
can someone please clos this
