### ISSUE TITLE
I wasn't able to use API until I added core dependency 

### ISSUE THREAD

**Issue by MelonCode** [MinusKube/Netherboard#19]
Greetings! Just started to use API, however, I wasn't able to use it until I added 
`implementation group: 'fr.minuskube', name: 'netherboard-core', version: '1.2.0'`
alongside with 
`implementation group: 'fr.minuskube', name: 'netherboard-bukkit', version: '1.2.0'`

My IDE was complaining about this. 
![image](https://user-images.githubusercontent.com/3682284/84598512-f9953a00-ae73-11ea-96b6-4be599f9bfde.png)

I'm not sure is this Intellij bug, or not, but thought that it might be a worthy thing to notify you about

**Comment by MinusKube** [comment]
Fixed in 1.2.1, will be available on Maven Central soon.
