### ISSUE TITLE
Readme copy & paste mistake

### ISSUE THREAD

**Issue by Paul2708** [MinusKube/Netherboard#21]
Hey,
the README contains
> put it in the plugins folder of your server, add it to your dependencies in your plugin.yml (e.g. `depend: [SmartInvs]`) and add it to the dependencies in your IDE.

and I think `[SmartInvs]` has to be replaced with `[Netherboard]`?

Greetings, Paul

**Comment by MinusKube** [comment]
Oops :x

**Comment by MinusKube** [comment]
Fixed, thanks :)
