### ISSUE TITLE
Plugin is not loaded

### ISSUE THREAD

**Issue by xXjojojXx** [MinusKube/Netherboard#23]
Sorry for my bad english with me the plugin is not loaded use the latest version of Forge and sponge would be happy if you could help me to fix the problem.////spongeforge-1.12.2-2838-7.2.4-RC4057////Netherboard-Sponge 
Or do I need anything else to get it going?

**Comment by MinusKube** [comment]
Do you have any error in the console?

**Comment by xXjojojXx** [comment]
Plugin 'netherboard' seems to be missing a valid mcmod.info metadata file. This is not a problem when testing plugins, however it is recommended to include one in public plugins.

**Comment by xXjojojXx** [comment]
Please do not use an abbreviation as far as sponge is concerned, I am not the expert.

**Comment by xXjojojXx** [comment]
put it in the plugins folder of your server, add it to your dependencies in your plugin.yml (e.g. depend: [Netherboard]) and add it to the dependencies in your IDE.
add it to the dependencies in your IDE and include it in your plugin jar.
That is the only thing I have found and not I am not doing so unfortunately you could explain step by step what has to be opened, what has to be inserted where and how it works.

**Comment by MinusKube** [comment]
If you take the first solution, you need to download the Sponge plugin [here](https://github.com/MinusKube/Netherboard/releases/tag/v1.2.1), and to put it in your server's "mods" folder, then in your own plugin, in the @Plugin annotation, add "Netherboard" to the dependencies

**Comment by xXjojojXx** [comment]
Do you have a discord?

**Comment by xXjojojXx** [comment]
I only ask for the reason that I can not quite understand what to insert there, so I asked about discord.

**Comment by xXjojojXx** [comment]
Because of the language barrier I would have an idea, maybe you could make a video on how to insert it so that it works.

**Comment by MinusKube** [comment]
Put the Netherboard plugin inside the **mods** folder of your SpongeForge server:
![image](https://user-images.githubusercontent.com/13206601/88461478-1aee3a80-cea4-11ea-9de5-f83691ddd4d5.png)

And inside your plugin's code, add `netherboard` to the dependencies:
![image](https://user-images.githubusercontent.com/13206601/88461485-36f1dc00-cea4-11ea-850a-0e6348b4f663.png)

**Comment by xXjojojXx** [comment]
Which program do I use to open it so that I can insert it?

**Comment by MinusKube** [comment]
Any IDE/text editor 🤔

**Comment by xXjojojXx** [comment]
So I can not insert anything because the file is read-only

**Comment by xXjojojXx** [comment]
![Unbenannt](https://user-images.githubusercontent.com/36734820/88538038-f5ca0b00-d00e-11ea-95b9-e36ea65a5288.PNG)

**Comment by MinusKube** [comment]
You must not edit the jar file, Netherboard is an API to make programming scoreboards easier, if you want to use it, you need to code your own plugin, and inside your own plugin, you'll find the `@Plugin`, and you'll be able to add the dependency.

**Comment by xXjojojXx** [comment]
Is there a way to just usSo if I understand that correctly, this is not a scoreboard, just a API, which is a shame, I'm looking for a functioning scoreboard.e the scoreboard without adding anything or to just write three and run.

**Comment by MinusKube** [comment]
Well, this is not the goal of Netherboard, maybe try [FeatherBoard](https://www.spigotmc.org/resources/featherboard.2691/), if I recall correctly, it's able to do what you're searching for.
