### ISSUE TITLE
Where's Netherboard lastest version (1.2.3) on maven?

### ISSUE THREAD

**Issue by imDMK** [MinusKube/netherboard#40]
```
        <dependency>
            <groupId>fr.minuskube</groupId>
            <artifactId>netherboard-bukkit</artifactId>
            <version>1.2.3</version>
        </dependency>
```
fr.minuskube:netherboard-bukkit:jar:1.2.3 was not found
Doesn't work.

**Comment by MinusKube** [comment]
Oops, forgot a step to release it! It should be available now, thanks :)

**Comment by imDMK** [comment]
Still was not found.

**Comment by MinusKube** [comment]
That must be some cache issue, I don't know how maven handles this, maybe there's a way to clean it. Otherwise, try again in a few hours
