### ISSUE TITLE
Update method?

### ISSUE THREAD

**Issue by MrJanek** [MinusKube/Netherboard#7]
Hello, I have an idea what could be added to this API. If it is possible, you could add a method like "UPDATE" which would update the scoreboard

**Comment by MinusKube** [comment]
Hello, you can already do that quite simply just by using a scheduler or something like that and just setting the lines, example:
```java
new BukkitRunnable() {
    private int time = 0;

    @Override
    public void run() {
        scoreboard.set("Time: " + time, 0);

        time++;
    }
}.runTaskTimer(plugin, 0, 20);
```
